name: Publish Docker

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to registy
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          registry: docker.pkg.github.com
          name: docker.pkg.github.com/scripac/top-api/top-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          tags: 'develop'
